#!/bin/bash

DELETE_FLAG=""

usage() {
  echo "Usage: copy-dir [--delete] <dir> <node-type>"
  exit 1
}

while :
do
  case $1 in
    --delete)
      DELETE_FLAG="--delete"
      shift
      ;;
    -*)
      echo "ERROR: Unknown option: $1" >&2
      usage
      ;;
    *) # End of options
      break
      ;;
  esac
done

if [[ "$#" != "2" ]] ; then
  usage
fi

NODE_TYPE=$2
DIR=`readlink -f "$1"`
DIR=`echo "$DIR"|sed 's@/$@@'`
DEST=`dirname "$DIR"`

NODES=`cat /root/spark-euca/$NODE_TYPE`

SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=5"

echo "RSYNC'ing $DIR to $NODE_TYPE..."
for node in $NODES; do
    echo $node
    rsync -e "ssh $SSH_OPTS" -az $DELETE_FLAG "$DIR" "$node:$DEST" & sleep 0.5
done
wait
